# Generated by Django 4.2.6 on 2023-10-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_fooditem_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='desciption',
            new_name='description',
        ),
    ]
